- name: nginx installation
  hosts: database
  tasks:
     - name: Install Nginx
       ansible.builtin.package:
         name: nginx
         state: installed

     - name: Start and enable service
       ansible.buildin.service:
         name: nginx
         state: started
         enabled: yes