- name: nginx installation
  hosts: database
  become: yes
  tasks:
     - name: Install Nginx
       ansible.builtin.package:
         name: nginx
         state: present

     - name: Start and enable service
       ansible.builtin.service:
         name: nginx
         state: started
         enabled: yes